name: ci
permissions:
  contents: read
on:
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.go }}
    strategy:
      matrix:
        go: [1.20.x, 1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go version
          go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          check-latest: true
      - run: |
          go version
          go test ./...
